apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-role
  namespace: jenkins-deployment
rules:
  - apiGroups: ["", "apps", extensions"]
    resources: ["deployments", "pods", "replicasets", "services"]
    verbs: ["*"]  