---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "jenkins-deployment-service"
  namespace: "jenkins-deployment"
  labels:
    app: "jenkins"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "jenkins"
  type: "LoadBalancer"
  loadBalancerIP: ""